class Phone:
    def __init__(self, phone: str) -> None:
        self.value = self.check_phone_validyti(phone)
    
    def check_phone_validyti(self, phone):
        ...
        ...
        ...
        return phone